services:
  blogging-db:
    image: postgres:15-alpine
    container_name: blogging-container
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-blogging-db}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:8.0-alpine
    container_name: blogging-cache
    restart: unless-stopped
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-your_default_password}
    command:
      [
        'redis-server',
        '--requirepass',
        '${REDIS_PASSWORD:-your_default_password}',
      ]
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  pgdata:
    name: school-management-db-data
    driver: local
  redis-data:
    name: redis-cache-data
    driver: local

networks:
  app-network:
    driver: bridge
